name: Deploy Atlas Cluster
on:
  workflow_dispatch:  
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
      - name: Terraform apply
        id: apply
        run: export MONGODB_ATLAS_PUBLIC_KEY=inprugnf &&
             export MONGODB_ATLAS_PRIVATE_KEY=2048c292-2cc4-4cc8-a991-d3aeb77d4847 &&
             terraform apply -auto-approve 
