name: Deploy Atlas Cluster
on:
  workflow_dispatch:  
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
      - name: Terraform apply
        id: apply
        run: export MONGODB_ATLAS_PUBLIC_KEY=dcgbyhle &&
             export MONGODB_ATLAS_PRIVATE_KEY=a86c763b-b7d3-4356-9cb0-54587010c449 &&
             terraform apply -auto-approve 
